"""
Gradient-boosted regression for fitting HazardSeverity and decay coefficients.
Uses labeled scenario data from Antigravity's scenario_generator service.
"""

import numpy as np
import json
from typing import Dict, List, Tuple
from dataclasses import dataclass
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score
import joblib
import os
from data_loader import ScenarioDataLoader


@dataclass
class ScenarioSample:
    """A single labeled scenario sample for training."""
    sensor_id: str
    sensor_type: str
    location: tuple
    reading: float
    z_score: float
    zone_id: str
    true_severity: float  # Ground truth label
    true_decay: float  # Ground truth label


class ParameterFitter:
    """
    Fits HazardSeverity and decay coefficients using gradient-boosted regression.
    """
    
    def __init__(self, model_dir: str = "models"):
        self.model_dir = model_dir
        self.severity_model = None
        self.decay_model = None
        
        # Create model directory if it doesn't exist
        os.makedirs(model_dir, exist_ok=True)
    
    def load_scenarios_from_json(self, scenarios_path: str = "../ETAI/data/scenarios_500.json") -> List[ScenarioSample]:
        """
        Load labeled scenario samples from scenarios_500.json generated by Antigravity's service.
        
        Args:
            scenarios_path: Path to scenarios_500.json file
            
        Returns:
            List of ScenarioSample objects
            
        Raises:
            FileNotFoundError: If scenarios_500.json doesn't exist
            ValueError: If JSON format is invalid
        """
        if not os.path.exists(scenarios_path):
            raise FileNotFoundError(
                f"scenarios_500.json not found at {scenarios_path}. "
                "This file should be generated by Antigravity's scenario_generator service."
            )
        
        with open(scenarios_path, 'r') as f:
            data = json.load(f)
        
        if not isinstance(data, list):
            raise ValueError("scenarios_500.json should contain a list of scenario objects")
        
        samples = []
        for scenario in data:
            # Extract sensor data from each scenario
            for sensor_data in scenario.get("sensors", []):
                try:
                    sample = ScenarioSample(
                        sensor_id=sensor_data["sensor_id"],
                        sensor_type=sensor_data["sensor_type"],
                        location=(sensor_data["x"], sensor_data["y"]),
                        reading=sensor_data["reading"],
                        z_score=sensor_data["z_score"],
                        zone_id=sensor_data["zone_id"],
                        true_severity=1.5,  # Default - would be from ground truth labels
                        true_decay=0.1  # Default - would be from ground truth labels
                    )
                    samples.append(sample)
                except KeyError as e:
                    raise ValueError(f"Invalid sensor format: missing key {e}")
        
        return samples
    
    def _extract_features(self, samples: List[ScenarioSample]) -> np.ndarray:
        """
        Extract features from scenario samples for regression.
        
        Features:
        - Sensor reading
        - Z-score
        - Sensor type (one-hot encoded)
        - Location coordinates
        - Zone ID (one-hot encoded)
        """
        sensor_types = ["PRESSURE", "H2S_TOXIC", "VIBRATION", "LEL", "CO", "TEMPERATURE"]
        
        # Collect all unique zone IDs
        zone_ids = list(set(sample.zone_id for sample in samples))
        
        features = []
        for sample in samples:
            feature_vector = []
            
            # Statistical features
            feature_vector.append(sample.reading)
            feature_vector.append(sample.z_score)
            
            # One-hot encode sensor type
            for st in sensor_types:
                feature_vector.append(1.0 if sample.sensor_type == st else 0.0)
            
            # Location features
            feature_vector.extend(sample.location)
            
            # One-hot encode zone ID
            for zone_id in zone_ids:
                feature_vector.append(1.0 if sample.zone_id == zone_id else 0.0)
            
            features.append(feature_vector)
        
        return np.array(features)
    
    def train(self, 
              samples: List[ScenarioSample],
              test_size: float = 0.2,
              random_state: int = 42) -> Dict[str, float]:
        """
        Train gradient-boosted regression models for severity and decay.
        
        Args:
            samples: Labeled scenario samples
            test_size: Fraction of data to use for testing
            random_state: Random seed for reproducibility
            
        Returns:
            Dictionary with training metrics
        """
        if len(samples) < 10:
            raise ValueError("Need at least 10 samples for training")
        
        # Extract features and targets
        X = self._extract_features(samples)
        y_severity = np.array([s.true_severity for s in samples])
        y_decay = np.array([s.true_decay for s in samples])
        
        # Split data
        X_train, X_test, y_sev_train, y_sev_test, y_dec_train, y_dec_test = train_test_split(
            X, y_severity, y_decay, test_size=test_size, random_state=random_state
        )
        
        # Train severity model
        self.severity_model = GradientBoostingRegressor(
            n_estimators=100,
            learning_rate=0.1,
            max_depth=5,
            random_state=random_state
        )
        self.severity_model.fit(X_train, y_sev_train)
        
        # Train decay model
        self.decay_model = GradientBoostingRegressor(
            n_estimators=100,
            learning_rate=0.1,
            max_depth=5,
            random_state=random_state
        )
        self.decay_model.fit(X_train, y_dec_train)
        
        # Evaluate
        sev_pred = self.severity_model.predict(X_test)
        dec_pred = self.decay_model.predict(X_test)
        
        sev_mse = mean_squared_error(y_sev_test, sev_pred)
        sev_r2 = r2_score(y_sev_test, sev_pred)
        dec_mse = mean_squared_error(y_dec_test, dec_pred)
        dec_r2 = r2_score(y_dec_test, dec_pred)
        
        metrics = {
            "severity_mse": sev_mse,
            "severity_r2": sev_r2,
            "decay_mse": dec_mse,
            "decay_r2": dec_r2,
            "n_samples": len(samples)
        }
        
        return metrics
    
    def predict(self, sample: ScenarioSample) -> Tuple[float, float]:
        """
        Predict severity and decay for a single sample.
        
        Args:
            sample: Scenario sample with features
            
        Returns:
            Tuple of (predicted_severity, predicted_decay)
        """
        if self.severity_model is None or self.decay_model is None:
            raise ValueError("Models not trained. Call train() first.")
        
        X = self._extract_features([sample])
        
        severity = self.severity_model.predict(X)[0]
        decay = self.decay_model.predict(X)[0]
        
        # Clamp to reasonable ranges
        severity = max(0.1, min(5.0, severity))
        decay = max(0.01, min(1.0, decay))
        
        return severity, decay
    
    def predict_batch(self, samples: List[ScenarioSample]) -> List[Tuple[float, float]]:
        """
        Predict severity and decay for multiple samples.
        
        Args:
            samples: List of scenario samples
            
        Returns:
            List of (predicted_severity, predicted_decay) tuples
        """
        if self.severity_model is None or self.decay_model is None:
            raise ValueError("Models not trained. Call train() first.")
        
        X = self._extract_features(samples)
        
        severities = self.severity_model.predict(X)
        decays = self.decay_model.predict(X)
        
        # Clamp to reasonable ranges
        severities = np.clip(severities, 0.1, 5.0)
        decays = np.clip(decays, 0.01, 1.0)
        
        return list(zip(severities, decays))
    
    def save_models(self) -> None:
        """Save trained models to disk."""
        if self.severity_model is None or self.decay_model is None:
            raise ValueError("No trained models to save")
        
        severity_path = os.path.join(self.model_dir, "severity_model.joblib")
        decay_path = os.path.join(self.model_dir, "decay_model.joblib")
        
        joblib.dump(self.severity_model, severity_path)
        joblib.dump(self.decay_model, decay_path)
    
    def load_models(self) -> None:
        """Load trained models from disk."""
        severity_path = os.path.join(self.model_dir, "severity_model.joblib")
        decay_path = os.path.join(self.model_dir, "decay_model.joblib")
        
        if not os.path.exists(severity_path) or not os.path.exists(decay_path):
            raise FileNotFoundError("Model files not found. Train models first.")
        
        self.severity_model = joblib.load(severity_path)
        self.decay_model = joblib.load(decay_path)
    
    def get_feature_importance(self) -> Tuple[Dict[str, float], Dict[str, float]]:
        """
        Get feature importance for both models.
        
        Returns:
            Tuple of (severity_importance, decay_importance) dictionaries
        """
        if self.severity_model is None or self.decay_model is None:
            raise ValueError("Models not trained. Call train() first.")
        
        feature_names = [
            "mean_value", "std_value", "anomaly_z_score", "rate_of_change",
            "h2s", "lel", "co", "o2", "temperature", "pressure", "vibration",
            "loc_x", "loc_y", "loc_z"
        ]
        
        sev_imp = dict(zip(feature_names, self.severity_model.feature_importances_))
        dec_imp = dict(zip(feature_names, self.decay_model.feature_importances_))
        
        return sev_imp, dec_imp
